main/default/objects/Account_Custom__c/Account_Custom__c.object-meta.xml
<CustomObject>
    <label>Account Custom</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounts Custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Account_Custom__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

main/default/objects/Account_Custom__c/fields/Account_Phone__c.field-meta.xml
<CustomField>
    <fullName>Account_Phone__c</fullName>
    <label>Account Phone</label>
    <type>Phone</type>
</CustomField>

main/default/classes/AccountProvider.cls
@RestResource(urlMapping='/myAccounts/*')
global class AccountProvider {

    @httpGet
    global static List<Account_Custom__c> getAllAccounts(){
               
	  RestRequest req = RestContext.request;
      RestResponse res = Restcontext.response;

      //String accountType = RestContext.request.params.get('accType');
      //String accountRating = RestContext.request.params.get('accRating');
        
        //if(String.isNotBlank(accountType) && String.isNotBlank(accountRating)){     
      		 return ([SELECT Id,Account_Name__c,Account_Phone__c,Account_Type__c,Name FROM Account_Custom__c]);
        /*}
        else{
            return null;
        }*/

    }
        /*@httpPut
    global static Account getAllAccounts(){
      RestRequest req = RestContext.request;
      RestResponse res = Restcontext.response;

      String jsonString=req.requestBody.tostring();
      responseWrapper objResWrap =(responseWrapper) JSON.deserialize(jsonString,responseWrapper.class);        
        
        Account objAcc = [select Id, Name,Type, Rating from Account where Name=:objResWrap.name LIMIT 1];
        objAcc.Rating = objResWrap.rating;
        Database.update(objAcc, false);
        
        
        return objAcc ;

    }
    
        global class responseWrapper{
		   global Id Id;
		   global string name;
		   global String type;
		   global String rating;  
		   global String sla; 
      }
*/
    
  
}