main/default/objects/Account_Custom__c/Account_Custom__c.object-meta.xml
<CustomObject>
    <label>Account Custom</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounts Custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Account_Custom__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

main/default/objects/Account_Custom__c/fields/Standard_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Standard_Account_ID__c</fullName>
    <externalId>true</externalId>
    <label>Standard Account ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

main/default/objects/Contact_Custom__c/Contact_Custom__c.object-meta.xml
<CustomObject>
    <label>Contact Custom</label>
    <nameField>
        <label>Contact Custom Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts Custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Contact_Custom__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account_Custom__c</referenceTo>
    <relationshipLabel>Contacts Custom</relationshipLabel>
    <relationshipName>Contacts_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Contact_Custom__c/fields/Updated_Record__c.field-meta.xml
<CustomField>
    <fullName>Updated_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Updated Record</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/custConController.cls
public class custConController {
	
    @auraEnabled
    public static Contact_Custom__c getcustCon(string key){
        //this methods return the Contact Custom record with the id provided to the component
        Contact_Custom__c objCustCon1 = new Contact_Custom__c();
        objCustCon1 = [select Id,First_Name__c,Last_Name__c,Account__c,Name,Account_Name__c,Account__r.Standard_Account_ID__c,Account__r.Name from Contact_Custom__c where Id=:key];
        
        return objCustCon1;
    }
    
    @Auraenabled
    public static Contact getoriginalCon(string key){
        //this methods return the Contact record related to Contact Custom with the id provided to the component
        Contact_Custom__c objCustCon2 = [select Id,First_Name__c,Last_Name__c,Account__c,Account_Name__c,Name from Contact_Custom__c where Id=:key];
        
        contact objCon;
        objCon = [select Id,FirstName,LastName,AccountId,Account.Name from Contact where Id=:objCustCon2.Name];
        return objCon;
        
    }
    
    @AuraEnabled
    public static string updateOriginalCon(Contact_Custom__c objCustCon){
        
         contact updateCon = [select Id,FirstName,LastName,AccountId,Account.Name from Contact where Id=:objCustCon.Name];
            updateCon.FirstName=objCustCon.First_Name__c;
            updateCon.LastName=objCustCon.Last_Name__c;
            updateCon.AccountId=objCustCon.Account__r.Standard_Account_ID__c;
            //updateCon.Id=objCustCon.Name;
       
update(updateCon);        
        Contact_Custom__c objCustConUpdate = [select Id,Updated_Record__c from Contact_Custom__c where Id=:objCustCon.Id];
       objCustConUpdate.Updated_Record__c = False;
        update(objCustConUpdate);
        
        system.debug('@@@@'+objCustConUpdate);
        
        return 'Success';
    }
    
    /* @AuraEnabled
    public static string rejectUpdatedCon(Contact_Custom__c objCustCon){
    Contact_Custom__c objCustConUpdate = [select Id,Updated_Record__c from Contact_Custom__c where Id=:objCustCon.Id];
       objCustConUpdate.Updated_Record__c = False;
        update(objCustConUpdate);
        
        system.debug('@@@@'+objCustConUpdate);
        return 'Success';
    }*/
}